-- MySQL Script generated by MySQL Workbench
-- Sat May  4 14:28:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDocTruyen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDocTruyen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDocTruyen` DEFAULT CHARACTER SET utf8 ;
USE `WebDocTruyen` ;

-- -----------------------------------------------------
-- Table `WebDocTruyen`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`User` (
  `idUser` INT NOT NULL,
  `ten` NVARCHAR(30) NULL,
  `sdt` FLOAT NULL,
  `email` NVARCHAR(40) NULL,
  `ngaysinh` DATETIME NULL,
  `diachi` NVARCHAR(40) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Danhmuc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Danhmuc` (
  `madanhmuc` INT NOT NULL,
  `tendanhmuc` NVARCHAR(45) NULL,
  PRIMARY KEY (`madanhmuc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Account` (
  `user_id` INT NOT NULL,
  `username` CHAR(45) NULL,
  `password` CHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Thanhtoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Thanhtoan` (
  `mathanhtoan` INT NOT NULL,
  `madonhang` INT NOT NULL,
  `sotien` FLOAT NULL,
  `thoigian` DATETIME NULL,
  `phuongthucthanhtoan` NVARCHAR(30) NULL,
  PRIMARY KEY (`mathanhtoan`, `madonhang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Truyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Truyen` (
  `matruyen` INT NOT NULL,
  `madanhmuc` INT NOT NULL,
  `tentruyen` NVARCHAR(45) NULL,
  `ngaydangtruyen` DATETIME NULL,
  `tacgiatruyen` NVARCHAR(45) NULL,
  `anhtruyen` NVARCHAR(45) NULL,
  `giatruyen` FLOAT NULL,
  `tihtrangtruyen` NVARCHAR(45) NULL,
  PRIMARY KEY (`matruyen`, `madanhmuc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Donhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Donhang` (
  `madohang` INT NOT NULL,
  `tenuser` NVARCHAR(45) NULL,
  `sdt` INT NULL,
  `motadonhag` NVARCHAR(45) NULL,
  `email` NVARCHAR(45) NULL,
  `diachi` NVARCHAR(45) NULL,
  `tongtien` INT NULL,
  `tongsp` INT NULL,
  PRIMARY KEY (`madohang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDocTruyen`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDocTruyen`.`Admin` (
  `idAdmin` INT NOT NULL,
  `user_admin` INT NULL,
  `password_admin` INT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
